-- GuardedTools -- what is left of an idea that did not work, and why.
--
-- V22 subclassed ClayRifle and PotatoLauncher, held their fire buttons shut, and
-- pointed our toolset at the subclasses. It looked right, the clay gun did stop
-- firing, and the whole thing was recorded as the fix.
--
-- IT NEVER RAN.
--
-- MEASURED, from the game log, which prints the class each uuid actually
-- resolved to at the moment a tool is created:
--
--   Created Tool 18 of type {8f190ce2-3a59-423e-8483-a7aa67bd5bc0(SurvivalLift)}
--
-- while our toolset was asking for class Lift on that uuid. Same story for
-- 6993e5df(ClayRifle) and a2a2bb33(PotatoLauncher) -- always the base class,
-- never ours, in every session.
--
-- A Custom Game's toolset can ADD a tool. It cannot OVERRIDE one the base
-- content already declares: the first declaration wins and the mod's is loaded
-- last. The proof that it is precedence and not a broken file is sitting in the
-- same toolset -- the nugdupS canary, a uuid nothing else declares, resolves
-- exactly as written.
--
-- So what actually stopped the clay gun? Game.client_onFixedUpdate, which calls
-- sm.tool.forceTool( nil ) on the client the instant a blocked uuid appears in
-- the player's hands. V22 moved that check from the server to the client in the
-- same build, and THAT is the change that worked. The subclasses were along for
-- the ride and got the credit.
--
-- The lesson worth keeping: two changes shipped together, one of them explains
-- the result, and picking the more interesting one is how a mod ends up carrying
-- code that has never executed.
--
-- What survives is this table. Nothing reads it any more except as the default
-- Game.client_setBlockedTools overwrites, but it is declared here so the name
-- has one obvious home.

g_swBlockedNames = g_swBlockedNames or {}
