"""Generate the crowd bot character set from vanilla's own in-game mechanics.

WHY THIS EXISTS, AND WHY THE FIRST DESIGN WAS WRONG
---------------------------------------------------

The bots used to be ONE characterset entry, dressed at runtime by
`character:overrideRenderableList( ... )` with a list assembled per bot. It gave
enormous variety and it cost the earth:

    0 bots   60.0 fps    233 bodies   714 shapes
    10 bots  15.0 fps    256 bodies   737 shapes
    20 bots   8   fps

Twenty-three extra bodies do not cost forty-five frames. The controlled
comparison was already in the logs: an earlier 95-bot run held **30 fps** while
the appearance code was throwing (every bot fell back to the characterset's own
outfit and therefore shared one renderable set). Working appearance, 20 bots,
8 fps. Broken appearance, 95 bots, 30 fps. The costume system was the load.

And vanilla says the same thing twice over:

  * `overrideRenderableList` is called in exactly ONE script in the whole game,
    for ONE quest NPC (GenericBuilderQuestCharacter).
  * vanilla's ten different-looking mechanics are ten CHARACTERSET ENTRIES, each
    with a fixed renderable list.

A fixed list per entry is loaded once and shared by every character using it. A
bespoke list per character is not shareable, and twenty of them is twenty sets of
meshes and textures the renderer cannot batch.

So the variety moves into the characterset, exactly as vanilla does it, and the
runtime does nothing but set a name tag.

Usage:  python dev/gen_characterset.py
"""
import io
import json
import os
import re

GAME = r"D:\SteamLibrary\steamapps\common\Scrap Mechanic"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "mod", "Characters", "Database", "CharacterSets",
                   "serverworks.characterset")

# Stable uuids, one per look. Generated once and then left alone: changing one
# would orphan any bot a saved world still refers to, and there is no reason to.
UUIDS = [
    "d465d7f2-c705-481d-8010-d3455839beed",   # kept from the single-entry version
    "b1f0a3c6-9d24-4e57-8a11-6c3f2b7d4e80",
    "c72e8d15-4b60-49af-93d2-1e5a8f06b7c3",
    "e3a95b48-7c11-4d26-8f70-2b6d9c4a5e17",
    "f0c41d97-2e83-4b15-9a6c-7d38e5b120f4",
    "a58b62e0-1f74-4c93-8d25-9e0a3b7c6d81",
    "9c17e4b3-6a58-4f02-b7d9-3e81c5a24f60",
    "84d3f0a7-5c92-4e61-8b03-7a1d6f95c2e8",
    "7b2c9e56-3d81-4a70-95f2-8c04b1e7d36a",
    "6e05a1d4-8f37-4c28-b619-2d7e93f5a04b",
    "5a94c3f8-7e20-4b61-8d53-1f68aptr0c92",   # placeholder, fixed below
]
UUIDS[10] = "5a94c3f8-7e20-4b61-8d53-1f68a0c92b37"


def load(p):
    t = io.open(p, encoding="utf-8-sig").read()
    t = re.sub(r"//[^\n]*", "", t)
    t = re.sub(r",(\s*[}\]])", r"\1", t)
    return json.loads(t)


def looks():
    """(name, sex, renderables) for every in-game mechanic, plus the player's own."""
    out = []
    d = load(os.path.join(GAME, "Survival", "Character", "CharacterSets",
                          "npc_mechanics.json"))
    for c in d["characters"]:
        sex = "female" if "female" in c["name"] else "male"
        out.append((c["name"], sex, list(c["renderables"])))

    # Data/Character/CharacterSets/default.json is what the game dresses the
    # PLAYER in -- the classic mechanic. A bot wearing it is wearing exactly what
    # a real player's character is built from.
    p = load(os.path.join(GAME, "Data", "Character", "CharacterSets",
                          "default.json"))
    out.append(("classic", "male", list(p["characters"][0]["renderables"])))
    return out


HEADER = """// SERVER WORKS -- the crowd bots.
//
// GENERATED by dev/gen_characterset.py. Do not hand-edit: re-run it instead,
// and re-run it after a game update in case vanilla's own mechanics change.
//
// One entry per LOOK, which is how vanilla gets ten different-looking mechanics
// (Survival/Character/CharacterSets/npc_mechanics.json) and is NOT how this mod
// did it at first. The bots used to be a single entry dressed at runtime by
// character:overrideRenderableList with a list built per bot. MEASURED cost of
// that, from /bench:
//
//     0 bots   60.0 fps      10 bots  15.0 fps      20 bots  8 fps
//
// against 30 fps for NINETY-FIVE bots in an earlier run where the appearance
// code was throwing and every bot silently shared the fallback outfit. A fixed
// renderable list per entry is loaded once and shared by every character that
// uses it; a bespoke list per character is twenty sets of meshes the renderer
// cannot batch.
//
// vanilla calls overrideRenderableList in exactly one script in the whole game,
// for one quest NPC. That was the tell, and it was there all along.
//
// The renderables below are copied verbatim from characters that exist in the
// game -- vanilla's ten NPC mechanics, plus the classic mechanic that
// Data/Character/CharacterSets/default.json dresses the PLAYER in. Nothing here
// is an asset a player could not see in game, which was the other half of the
// problem: the hand-built lists pulled in cosmetics that are on disk and not
// obtainable.
//
// The capsule, hit hulls, ragdoll and tumble hull are vanilla's own for a human.
// The MOVEMENT block is the PLAYER's, out of default.json, because a stand-in
// for a player should move at a player's speed -- vanilla's NPC mechanics sprint
// at 8.0, which is twice as fast as anyone.
"""

ENTRY = """\t\t{{
\t\t\t"capsule" : {{ "crouchHeight" : 0.8, "height" : 1.4, "radius" : 0.3 }},
\t\t\t"character" : {{
\t\t\t\t"data" : {{}},
\t\t\t\t"scriptClass" : "BotCharacter",
\t\t\t\t"scriptPath" : "$CONTENT_DATA/Scripts/BotCharacter.lua"
\t\t\t}},
\t\t\t"hit" : {{
\t\t\t\t"crouch" : {{
\t\t\t\t\t"col" : "$SURVIVAL_DATA/Character/Char_Male/char_male_hit_crouch_col.obj",
\t\t\t\t\t"offset" : [ 0.0, 0.0, 0.4 ]
\t\t\t\t}},
\t\t\t\t"stand" : {{
\t\t\t\t\t"col" : "$SURVIVAL_DATA/Character/Char_Male/char_male_hit_stand_col.obj",
\t\t\t\t\t"offset" : [ 0.0, 0.0, 0.7 ]
\t\t\t\t}}
\t\t\t}},
\t\t\t"mass" : 120.0,
\t\t\t"material" : "RagdollHuman",
\t\t\t"movement" : {{
\t\t\t\t"canSwim" : true,
\t\t\t\t"crouchSpeed" : 3.0,
\t\t\t\t"facingRotationSpeed" : 3.1415,
\t\t\t\t"headingRotationSpeed" : 3.1415,
\t\t\t\t"jumpImpulse" : 7.0,
\t\t\t\t"moveSpeed" : 1.4575,
\t\t\t\t"slowDownSpeed" : 2.5,
\t\t\t\t"sprintSpeed" : 4.0
\t\t\t}},
\t\t\t"ragdoll" : "$SURVIVAL_DATA/Character/Char_Male/char_male_ragdoll.json",
\t\t\t"renderables" : [
{rends}
\t\t\t],
\t\t\t"tumble" : {{
\t\t\t\t"col" : "$SURVIVAL_DATA/Character/Char_Male/char_male_col.obj",
\t\t\t\t"offset" : [ 0.0, 0.0, 0.683 ]
\t\t\t}},
\t\t\t"unit" : {{
\t\t\t\t"data" : {{}},
\t\t\t\t"scriptClass" : "BotUnit",
\t\t\t\t"scriptPath" : "$CONTENT_DATA/Scripts/BotUnit.lua"
\t\t\t}},
\t\t\t"uuid" : "{uuid}",
\t\t\t"name" : "sw_crowd_{name}",
\t\t\t"showInEditor" : false
\t\t}}"""


def main():
    got = looks()
    assert len(got) <= len(UUIDS), f"{len(got)} looks but only {len(UUIDS)} uuids"

    entries = []
    for i, (name, sex, rends) in enumerate(got):
        body = ",\n".join(f'\t\t\t\t"{r}"' for r in rends)
        entries.append(ENTRY.format(rends=body, uuid=UUIDS[i], name=name))

    text = HEADER + "{\n\t\"characters\" :\n\t[\n" + ",\n".join(entries) + "\n\t]\n}\n"
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(text)

    print(f"wrote {len(got)} looks to {os.path.relpath(OUT, ROOT)}")
    for i, (name, sex, rends) in enumerate(got):
        print(f"  {UUIDS[i]}  sw_crowd_{name:16} {sex:7} {len(rends)} renderables")

    # The uuid list Crowd.lua needs, ready to paste.
    print("\nCrowd.BOT_UUIDS = {")
    for i, (name, _, _) in enumerate(got):
        print(f'\t"{UUIDS[i]}",   -- {name}')
    print("}")


if __name__ == "__main__":
    main()
